export const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  USER_EXISTS: "USER_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  USER_BLOCKED: "USER_BLOCKED",
  VEHICLE_ALREADY_EXISTS: "VEHICLE_ALREADY_EXISTS",
  VEHICLE_NOT_AVAILABLE: "VEHICLE_NOT_AVAILABLE",
  ACTIVE_RENTAL_EXISTS: "ACTIVE_RENTAL_EXISTS",
  INVALID_RENTAL_STATE: "INVALID_RENTAL_STATE",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
